// Long-form body + FAQ content for the three pillar pages.
// Generated from the master content doc and edited in src/lib/pillars.ts.

export interface Faq { q: string; a: string }
export interface Pillar { body: string[]; faqs: Faq[] }

export const traumaTherapy: Pillar = {
  body: [
    "h2: Trauma Therapy in Austin, TX",
    "Evidence-based care for PTSD, complex trauma, anxiety, and grief — without being rushed.",
    "If you're searching for trauma therapy in Austin, you're likely already carrying more than most people realize. Maybe a single event keeps replaying in your mind. Maybe the past is showing up in your body, your relationships, or your sleep. Maybe you've been \"fine\" for a long time, and lately fine has stopped working.",
    "Haven & Harbor Counseling is a small, intentional practice in Austin focused on doing trauma therapy well. The work is unhurried, evidence-based, and shaped to your nervous system. You stay in control of what you share, when you share it, and how fast we move.",
    "Brittany Zientek, LPC, has eight years of clinical experience treating PTSD, complex trauma, anxiety, and relationship concerns using EMDR, Internal Family Systems (IFS), and Trauma-Focused CBT. Faith is welcome when you want it; the work stands on its own when you don't.",
    "h2: What kind of trauma we treat",
    "Trauma is not one thing. The therapy that helps a car accident is different from the therapy that helps childhood neglect, and both differ from the therapy that helps spiritual abuse. Brittany works with all of these.",
    "PTSD (post-traumatic stress disorder)",
    "Symptoms that show up after a discrete event: car accidents, assault, medical trauma, a sudden loss, military or first-responder exposure, witnessing violence. PTSD often looks like flashbacks, nightmares, hypervigilance, avoidance, and a nervous system that can't quite tell the difference between then and now.",
    "EMDR is a first-line treatment for single-incident PTSD, recommended by the APA, the WHO, and the VA. Many clients see meaningful improvement in 8–12 sessions.",
    "Complex trauma (C-PTSD)",
    "Ongoing experiences — usually beginning in childhood — that shape how the nervous system, the sense of self, and relationships develop. Emotional neglect, abuse, family dysfunction, attachment wounds, growing up in a high-conflict or high-control home. Complex trauma rarely looks like a single memory. It looks like patterns: chronic shame, people-pleasing, difficulty trusting, a fragile sense of self, anxiety that has no obvious cause.",
    "Complex trauma takes longer than single-incident trauma — typically several months of stabilization before deeper memory work, and often a year or more of overall therapy. IFS is especially well-suited for this work, because it honors the protective parts of you that helped you survive.",
    "h2: Religious and spiritual trauma",
    "Church hurt, spiritual abuse, high-control religious environments, manipulative leaders, and the long shadow they leave on your faith, body, and relationships. This work requires a therapist who can hold both the psychological and the spiritual without weaponizing either. Brittany does. Learn more about our approach to Christian counseling →.",
    "h2: Trauma-related anxiety and grief",
    "Chronic anxiety, panic, hypervigilance, and complicated grief that traces back to earlier wounds. Many adults walking into therapy with anxiety as the presenting issue are actually walking in with untreated trauma. Sometimes the most direct path to peace runs through the past.",
    "h2: How we work — three evidence-based modalities",
    "EMDR (Eye Movement Desensitization and Reprocessing)",
    "EMDR helps the brain finish processing memories that still feel raw. Through bilateral stimulation — typically eye movements or light tapping — your brain is able to integrate stuck memories into your broader life story, so they stop hijacking the present.",
    "EMDR has more clinical research behind it than almost any trauma treatment. It is a first-line PTSD treatment recommended by the APA, the WHO, and the VA. It works in-person and via telehealth (with small adjustments). Learn more about EMDR therapy →.",
    "Internal Family Systems (IFS)",
    "IFS understands you as a system of \"parts\" — the protective part that doesn't trust people, the perfectionist part that drives you, the wounded part that learned to stay quiet. None of these parts are bad. They learned to keep you safe.",
    "In IFS, we get to know each of those parts with curiosity rather than fight them. The protective parts can step back. The wounded parts can be tended to. Over time, the system reorganizes around the Self — calm, compassionate, present. IFS is especially powerful for complex trauma. Learn more about IFS →.",
    "h2: Trauma-Focused CBT",
    "Structured, well-researched cognitive-behavioral work that gently restructures the thoughts and beliefs trauma left behind (\"I'm not safe,\" \"I'm too much,\" \"It was my fault\"). Brittany pairs it with traditional CBT, mindfulness-based cognitive therapy (MBCT), and solution-focused brief therapy depending on what your nervous system needs.",
    "h2: What a course of trauma therapy looks like",
    "We follow the phase-based model that's standard in trauma treatment. You stay in control at every stage.",
    "Phase 1 — Stabilization. Before any memory work, we build resources: tools for nervous-system regulation, grounding, safety planning, and a clearer sense of what we're working with. For some clients this takes a few sessions; for others, several months. There's no rush.",
    "Phase 2 — Reprocessing. Using EMDR and/or IFS, we work through the memories and parts that drive current symptoms. This is the part most people imagine when they think of \"trauma therapy,\" but it only happens after stabilization is solid.",
    "Phase 3 — Integration. We translate the shifts into your daily life — relationships, work, faith, body, identity. The wins stick because they're integrated.",
    "Throughout, you decide what to share and when. Trauma therapy that retraumatizes is bad trauma therapy. We don't do that here.",
    "h2: Practical details — insurance, cost, location",
    "h2: In-network with most major plans",
    "Through Headway, Brittany is in-network with Aetna, Cigna, United Healthcare, Oscar, Oxford, and Anthem. Most clients with these plans see therapy covered with a standard copay.",
    "Self-pay rates",
    "Self-pay sessions are $130–$225 depending on session type. Superbills are available for out-of-network reimbursement. See the full cost of therapy in Austin →.",
    "h2: Office location",
    "The Austin office is at 6448 East Hwy 290, Ste E108, Austin, TX 78723. Easy parking, quiet waiting area, no walk-by traffic.",
    "h2: Telehealth across Texas",
    "EMDR and IFS work well via secure telehealth platforms, with small adjustments. Telehealth is available for any client physically located in Texas at the time of session.",
    "h2: Meet your therapist",
    "Brittany Zientek, LPC — Licensed Professional Counselor in Texas, eight years of clinical experience in trauma, anxiety, PTSD, and relationship concerns. Trained in EMDR, IFS, Trauma-Focused CBT, CBT, MBCT, and Solution-Focused Brief Therapy.",
    "Warm, collaborative, and committed to going at your pace. Faith-friendly without being faith-required.",
    "More about Brittany →",
  ],
  faqs: [
    { q: "What's the difference between trauma therapy and regular talk therapy?", a: "Trauma therapy goes beyond talking about what happened. Talking about a traumatic memory can sometimes deepen the impression of it rather than resolve it. Trauma-focused modalities like EMDR and IFS help the brain and body finish processing what was never fully metabolized — so the memory still exists, but it loses its grip on your present." },
    { q: "How do I know if I need trauma therapy?", a: "If something from your past keeps showing up in your present — through anxiety, hypervigilance, avoidance, relationship patterns, or a feeling that \"something's wrong but I don't know what\" — trauma therapy is worth exploring. You don't need a Big-T trauma to benefit. Many clients come in with anxiety or grief and discover trauma was underneath." },
    { q: "Is EMDR covered by insurance in Texas?", a: "Yes. EMDR is a billable psychotherapy modality, not a separate service. If your plan covers therapy with Brittany, it covers EMDR with Brittany." },
    { q: "Can trauma therapy be done over telehealth?", a: "Yes. EMDR and IFS both work well via secure telehealth platforms. Many clients prefer telehealth because being in their own environment helps regulation. Some prefer in-person for the same reason. Both work." },
    { q: "How long does trauma therapy take?", a: "Single-incident trauma (an accident, an assault, a sudden loss) often improves significantly in 8–12 sessions with EMDR. Complex or developmental trauma typically takes longer — several months of stabilization before deeper reprocessing, and often a year or more of overall work. We'll talk about expected pacing in the consult." },
    { q: "Will I have to talk about everything that happened?", a: "No. EMDR specifically works without requiring you to narrate every detail aloud. IFS works with the parts of you that hold the memories rather than the memories themselves. You stay in control of what you share." },
    { q: "What if my trauma is spiritual or religious in nature?", a: "That's part of what we do here. Religious trauma — church hurt, spiritual abuse, high-control environments — gets the same trauma-informed approach with care for your current relationship with faith, whatever it is. See the Christian counseling page →." },
    { q: "Ready to take the first step?", a: "You don't have to have it figured out. You don't have to know whether what happened \"counts.\" You just have to be willing to start a conversation. Schedule a free 15-minute consult to see if Haven & Harbor is the right fit. No pressure, no commitment — just a conversation." },
  ],
};

export const christianCounseling: Pillar = {
  body: [
    "h2: Christian Counseling in Austin, TX",
    "Licensed, faith-integrated therapy — on your terms, at your pace.",
    "If you're looking for Christian counseling in Austin, you probably want two things at once: real, evidence-based therapy and a clinician who can speak the language of your faith. Not pastoral counseling. Not Bible study with a couch. Not someone who is going to weaponize scripture when you're already hurting.",
    "Haven & Harbor Counseling is a licensed mental-health practice in Austin where Christian clients can do serious psychological work without leaving their faith at the door. Sessions hold scripture, prayer, and theology with the same care we hold psychology and the nervous system. Both matter. Both belong.",
    "Brittany Zientek, LPC, is a Licensed Professional Counselor with eight years of clinical experience. She's trained in EMDR, Internal Family Systems (IFS), and Trauma-Focused CBT — and she's also a Christian. The integration is real, not bolted on.",
    "h2: What \"Christian counseling\" actually means here",
    "The phrase \"Christian counseling\" gets used to mean a lot of different things. Here's what it means at Haven & Harbor.",
    "It's not pastoral counseling. Pastoral counseling is a beautiful and important ministry, but it's not the same as licensed mental-health treatment. Brittany is a Licensed Professional Counselor, with the clinical training, supervision hours, and continuing education the state of Texas requires.",
    "It's not Bible study with extra steps. Sessions are not built around scripture. They are built around your healing. Scripture and prayer enter the room when you want them to enter the room.",
    "It is licensed, evidence-based therapy with room for your faith. Same modalities, same standards of care, same confidentiality, same insurance billing as any other therapy in Austin. The difference is that your therapist can sit comfortably with words like grace, repentance, sanctification, the Holy Spirit, or \"I think God is using this season to show me something\" — and not flatten any of it.",
    "h2: Who Christian counseling is for",
    "Most clients who choose Christian counseling at Haven & Harbor are walking in with at least one of the following:",
    "ul: Church hurt or spiritual abuse — a pastor, a community, a leader, or a doctrine that wounded you, and a faith that hasn't recovered yet. | Performance-based or shame-based religion — growing up believing your worth depended on your behavior, your service, your purity, or your usefulness. | Trauma alongside faith — the way trauma scrambles your sense of God's character, your prayers, your felt sense of being loved. | Anxiety and perfectionism — the high-functioning Christian who has never given themselves permission to rest. | Faith deconstruction or reconstruction — the season where what you used to believe stopped fitting, and you're trying to figure out what you actually believe now. | Marriage, identity, and life transitions in a faith context — career shifts, motherhood, singleness, midlife, all held in the larger story you understand your life to be part of. | Grief, doubt, and dark nights of the soul — when prayer stops feeling like prayer, and you wonder if anyone is listening.",
    "You don't have to be in a tidy place with your faith to be here. Most of us aren't.",
    "h2: How faith shows up in sessions",
    "You set the spiritual temperature of the room. Every week. It can change session to session.",
    "Some sessions include:",
    "ul: Sitting with a passage of scripture together | Beginning or ending in prayer | Talking about your image of God and how trauma may have shaped it | Working through theological questions tied to what you're processing | IFS work with the \"spiritual parts\" of you — the part that prays, the part that doubts, the part that performs",
    "Some sessions never mention faith at all. That's also a full session of Christian counseling, because the therapist still understands and respects the frame of your life.",
    "You will never be:",
    "ul: Prayed over without consent. | Handed homework that assumes a doctrinal position. | Pushed back toward certainty when you're in the middle of doubting. | Diagnosed with a \"spiritual problem\" instead of a clinical one.",
    "h2: Common reasons clients come — in more detail",
    "h2: Church hurt and spiritual abuse",
    "Sometimes the people meant to shepherd you wounded you instead. Sometimes the community you trusted protected the wrong person. Sometimes you were taught that your body, your questions, or your femininity were the problem. The work here is to help the wound name itself, to help your nervous system finish what it couldn't finish while the harm was still happening, and to make space for the relationship with God that's underneath all of it to be re-examined honestly.",
    "h2: Faith deconstruction",
    "Deconstruction is not the same as walking away from faith. For most clients, it's the slow and often painful process of separating what they were taught from what scripture actually says from what they have personally experienced of God. The goal of therapy is not to defend a particular theology. It's to help you do the work in a way that honors your nervous system, your relationships, and your story.",
    "h2: Religious trauma",
    "A specific category of trauma where the wounding happened through religious systems, leaders, or beliefs. It often looks like classic PTSD or complex trauma symptoms, but with a layer of spiritual disorientation. EMDR and IFS both work well with religious trauma.",
    "h2: Anxiety and perfectionism in faith contexts",
    "Many Christian clients carry an unspoken belief that anxiety is a spiritual failure — that if they prayed more or trusted more, they wouldn't feel this way. That belief makes the anxiety worse. The work here is gentler than that: holding both the body and the soul with care, and letting evidence-based treatment do what it does.",
    "h2: The modalities — same standards of care as any Austin therapist",
    "EMDR",
    "A first-line PTSD treatment that works particularly well for religious trauma and for the specific kinds of memories that have a doctrinal layer attached. Learn more →.",
    "Internal Family Systems (IFS)",
    "IFS is uniquely well-suited for Christian clients because it does not flatten the spiritual life into psychology. Your \"parts\" — the protector, the perfectionist, the wounded child — are not all there is to you. The Self in IFS resonates strongly with what many Christians call the soul or the imago Dei. Learn more →.",
    "h2: Trauma-Focused CBT, CBT, MBCT, SFBT",
    "Supporting modalities Brittany draws on as appropriate.",
    "h2: Practical details",
    "Insurance: Through Headway — Aetna, Cigna, United Healthcare, Oscar, Oxford, and Anthem are all in-network.",
    "Self-pay: $130–$225 per session. Superbills available for out-of-network reimbursement.",
    "Location: 6448 East Hwy 290, Ste E108, Austin, TX 78723. Telehealth available across Texas.",
    "Free 15-minute consult: No-pressure phone or video conversation to see if we're a good fit.",
  ],
  faqs: [
    { q: "What is Christian counseling, exactly?", a: "Christian counseling at Haven & Harbor is licensed, evidence-based therapy provided by a clinician who can integrate Christian faith into the work when the client wants it. It is not pastoral counseling, not a Bible study, not a substitute for a church community. It is real therapy with room for your faith." },
    { q: "Is this licensed therapy or pastoral counseling?", a: "Licensed therapy. Brittany Zientek is a Licensed Professional Counselor in Texas. Sessions are confidential, billable to insurance, and held to the same clinical standards as any other Austin therapy practice." },
    { q: "Will you pray with me or use scripture in sessions?", a: "Only if you want me to. You set the spiritual temperature of the room every week. Some clients want every session to include prayer; some never want faith mentioned in the work but still want a Christian therapist. Both are valid, and both can change over time." },
    { q: "Do you accept insurance for Christian counseling?", a: "Yes. Through Headway, Brittany is in-network with Aetna, Cigna, United Healthcare, Oscar, Oxford, and Anthem. Christian counseling is billed the same as any other therapy." },
    { q: "Do you offer in-person or online Christian counseling?", a: "Both. The Austin office is at 6448 E Hwy 290, Ste E108. Telehealth is available across Texas." },
    { q: "What if I'm deconstructing or unsure what I believe?", a: "You're welcome here. Many clients come in the middle of deconstruction or church hurt. The work is to help you heal — not to defend a particular theology or rush you back to certainty." },
    { q: "Do you work with people who used to be Christian but aren't sure anymore?", a: "Yes. Therapy is not contingent on what you currently believe. It is contingent on what you're working through." },
    { q: "What denominations do you work with?", a: "All of them. Catholic, Orthodox, Protestant (every flavor), non-denominational, charismatic, formerly-religious. The shape of your faith story is yours." },
    { q: "Can I see a Christian therapist who also takes my insurance?", a: "Yes — that's a big part of why Haven & Harbor exists. See the in-network plans above. You don't have to choose between faith and healing. Schedule a free 15-minute consult to see if Haven & Harbor is the right fit. No pressure, no commitment — just a conversation." },
  ],
};

export const anxietyTherapy: Pillar = {
  body: [
    "h2: Anxiety Therapy in Austin, TX",
    "When your mind won't slow down — evidence-based help for chronic worry, panic, perfectionism, and the weight of always being \"on.\"",
    "If you're searching for anxiety therapy in Austin, the day-to-day probably looks different than people realize. From the outside you may be holding it together — hitting deadlines, showing up for people, even thriving on paper. On the inside, the mind doesn't stop. The body doesn't rest. Sleep is shallow. Decisions feel impossible. The smallest thing can pull the floor out from under you.",
    "Haven & Harbor Counseling is a small Austin practice that does anxiety therapy the way anxiety actually needs to be treated — with care for both the racing thoughts and the body underneath them. The work is evidence-based, unhurried, and shaped to who you actually are.",
    "Brittany Zientek, LPC, has eight years of experience treating anxiety in adults, including high-functioning anxiety, panic disorder, generalized anxiety, social anxiety, perfectionism, and anxiety driven by underlying trauma.",
    "h2: What kind of anxiety we treat",
    "Anxiety is not one thing, and the right treatment depends on what's actually going on. Brittany works with all of the following.",
    "h2: High-functioning anxiety",
    "The kind nobody else sees. You're competent, organized, often praised for being reliable — and underneath, your nervous system is running hot most of the day. Rest feels unsafe. Doing nothing feels impossible. You may experience tension headaches, jaw clenching, GI issues, or chronic shoulder pain that doesn't have a medical cause.",
    "Generalized anxiety disorder (GAD)",
    "Chronic, free-floating worry about a lot of things at once. The \"what ifs\" that won't stop. The anticipation that something is about to go wrong. Often comes with restlessness, fatigue, difficulty concentrating, irritability, and sleep that doesn't refresh.",
    "h2: Panic disorder and panic attacks",
    "Sudden waves of intense fear, often with physical symptoms — racing heart, shortness of breath, chest tightness, dizziness, a feeling that something terrible is about to happen. Panic disorder includes the fear of having another attack, which can spiral into avoidance of places or situations.",
    "h2: Social anxiety",
    "Anxiety in interpersonal contexts — public speaking, meetings, parties, dating, even one-on-one conversations. Often paired with a chronic sense of being evaluated and a habit of post-event rumination.",
    "Perfectionism",
    "Often labeled as a personality trait when it's actually anxiety wearing a more socially acceptable costume. The driving belief is that mistakes are catastrophic and that your worth is contingent on output.",
    "h2: Anxiety driven by underlying trauma",
    "Many adults who walk in with anxiety as the chief complaint discover, in the work, that trauma is underneath it. The anxiety was the nervous system's adaptation to an environment that wasn't safe. When the trauma gets treated, the anxiety quiets dramatically.",
    "h2: How we treat anxiety",
    "There is no one-size-fits-all anxiety treatment. The right approach depends on what's driving your specific anxiety and what your nervous system needs.",
    "Cognitive Behavioral Therapy (CBT)",
    "The most well-researched anxiety treatment. CBT helps you identify the thought patterns that feed anxiety (catastrophizing, mind-reading, all-or-nothing thinking) and develop concrete tools for working with them. Especially effective for generalized anxiety, social anxiety, and panic.",
    "Mindfulness-Based Cognitive Therapy (MBCT)",
    "A hybrid of CBT and mindfulness that helps you change your relationship with anxious thoughts rather than fight them. Particularly helpful for chronic worry and rumination.",
    "EMDR",
    "When anxiety has a trauma component — and it very often does — EMDR helps the brain finish processing what's underneath. Often dramatically reduces anxiety symptoms once the underlying material is integrated. Learn more →.",
    "Internal Family Systems (IFS)",
    "Treats anxiety as a protective part of you that learned to scan for threat — and rather than trying to silence that part, gets to know it. Anxiety, in IFS, often quiets when the wounded parts it's protecting feel tended to. Learn more →.",
    "Solution-Focused Brief Therapy (SFBT)",
    "Used in shorter courses of work when anxiety is tied to a specific life transition or stressor.",
    "h2: Somatic and nervous-system work",
    "Across modalities, Brittany pays attention to what your body is doing. Anxiety lives in the body, and any treatment that ignores that leaves results on the table. We build practical tools for regulation, grounding, and titrated rest.",
    "h2: What treatment usually looks like",
    "Sessions 1–3. We get to know what we're working with — your history, your symptoms, what's tried, what hasn't, what your life looks like right now. We start building immediate tools you can use this week.",
    "Sessions 4–10. The active work — depending on what's driving the anxiety, this is CBT skill-building, MBCT practice, EMDR reprocessing, IFS work with the anxious parts, or some combination. Most clients start to notice meaningful change by week 6–8.",
    "Maintenance. Many clients move to biweekly or monthly sessions once symptoms quiet, then taper off. Some come back periodically when life shifts.",
    "For pure anxiety without significant trauma, most clients see meaningful improvement in 12–20 sessions. Anxiety driven by underlying trauma takes longer, because we're treating the cause rather than the symptom.",
    "h2: Practical details",
    "Insurance: Through Headway — Aetna, Cigna, United Healthcare, Oscar, Oxford, and Anthem are all in-network.",
    "Self-pay: $130–$225 per session. Superbills available for out-of-network reimbursement.",
    "Location: 6448 East Hwy 290, Ste E108, Austin, TX 78723. Telehealth across Texas.",
    "h2: Meet your therapist",
    "Brittany Zientek, LPC — Licensed Professional Counselor in Texas with eight years of clinical experience. Trained in CBT, MBCT, EMDR, IFS, Trauma-Focused CBT, and Solution-Focused Brief Therapy. Warm, collaborative, and committed to going at your pace.",
    "More about Brittany →",
  ],
  faqs: [
    { q: "How do I know if my anxiety is bad enough to need therapy?", a: "If anxiety is affecting your sleep, your relationships, your work, or your sense of yourself — and especially if it's been going on for more than a few months — therapy is reasonable. You don't need to be in crisis to benefit. Most clients say they wish they had come in sooner." },
    { q: "How long does anxiety therapy take?", a: "For pure anxiety without significant underlying trauma, most clients see meaningful improvement in 12–20 sessions. Some need fewer; some need more. Anxiety driven by underlying trauma typically takes longer because we're treating the root rather than the surface." },
    { q: "Is anxiety therapy covered by insurance in Austin?", a: "Yes. Through Headway, Brittany is in-network with Aetna, Cigna, United Healthcare, Oscar, Oxford, and Anthem. Anxiety treatment is billed the same as any other psychotherapy." },
    { q: "What's the difference between anxiety therapy and medication?", a: "Therapy and medication treat anxiety through different mechanisms and often work well together. Therapy addresses the patterns of thought, behavior, and underlying experience driving the anxiety; medication addresses the brain chemistry making those patterns more intense. Brittany is happy to coordinate with a prescribing psychiatrist if medication is part of your treatment plan." },
    { q: "Can anxiety therapy be done over telehealth?", a: "Yes. CBT, MBCT, EMDR, and IFS all work well over secure telehealth platforms. Many clients prefer telehealth because being in their own space helps with regulation." },
    { q: "What if my anxiety comes from trauma?", a: "That's common — and often the most important thing to know. When anxiety is downstream of trauma, treating the anxiety alone produces partial results. Treating the trauma underneath produces durable change. See the trauma therapy page →." },
    { q: "Do you work with high-functioning anxiety?", a: "Yes. Brittany has significant experience with high-functioning anxiety — the kind that's invisible to other people and exhausting to live inside. The work often involves giving yourself permission to actually rest, which is harder than it sounds." },
    { q: "Can I integrate my faith into anxiety therapy?", a: "Yes. Faith is welcome in the work when you want it. See the Christian counseling page →. You don't have to keep running this hot. Schedule a free 15-minute consult to see if Haven & Harbor is the right fit. No pressure, no commitment — just a conversation." },
  ],
};
