/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChristianCounselingRouteImport } from './routes/christian-counseling'
import { Route as AustinTraumaTherapistRouteImport } from './routes/austin-trauma-therapist'
import { Route as AustinTherapyRouteImport } from './routes/austin-therapy'
import { Route as AustinTherapistRouteImport } from './routes/austin-therapist'
import { Route as AustinChristianTherapistRouteImport } from './routes/austin-christian-therapist'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChristianCounselingRoute = ChristianCounselingRouteImport.update({
  id: '/christian-counseling',
  path: '/christian-counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinTraumaTherapistRoute = AustinTraumaTherapistRouteImport.update({
  id: '/austin-trauma-therapist',
  path: '/austin-trauma-therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinTherapyRoute = AustinTherapyRouteImport.update({
  id: '/austin-therapy',
  path: '/austin-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinTherapistRoute = AustinTherapistRouteImport.update({
  id: '/austin-therapist',
  path: '/austin-therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinChristianTherapistRoute =
  AustinChristianTherapistRouteImport.update({
    id: '/austin-christian-therapist',
    path: '/austin-christian-therapist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/austin-christian-therapist': typeof AustinChristianTherapistRoute
  '/austin-therapist': typeof AustinTherapistRoute
  '/austin-therapy': typeof AustinTherapyRoute
  '/austin-trauma-therapist': typeof AustinTraumaTherapistRoute
  '/christian-counseling': typeof ChristianCounselingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/austin-christian-therapist': typeof AustinChristianTherapistRoute
  '/austin-therapist': typeof AustinTherapistRoute
  '/austin-therapy': typeof AustinTherapyRoute
  '/austin-trauma-therapist': typeof AustinTraumaTherapistRoute
  '/christian-counseling': typeof ChristianCounselingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/austin-christian-therapist': typeof AustinChristianTherapistRoute
  '/austin-therapist': typeof AustinTherapistRoute
  '/austin-therapy': typeof AustinTherapyRoute
  '/austin-trauma-therapist': typeof AustinTraumaTherapistRoute
  '/christian-counseling': typeof ChristianCounselingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/austin-christian-therapist'
    | '/austin-therapist'
    | '/austin-therapy'
    | '/austin-trauma-therapist'
    | '/christian-counseling'
    | '/contact'
    | '/faq'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/austin-christian-therapist'
    | '/austin-therapist'
    | '/austin-therapy'
    | '/austin-trauma-therapist'
    | '/christian-counseling'
    | '/contact'
    | '/faq'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/austin-christian-therapist'
    | '/austin-therapist'
    | '/austin-therapy'
    | '/austin-trauma-therapist'
    | '/christian-counseling'
    | '/contact'
    | '/faq'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  AustinChristianTherapistRoute: typeof AustinChristianTherapistRoute
  AustinTherapistRoute: typeof AustinTherapistRoute
  AustinTherapyRoute: typeof AustinTherapyRoute
  AustinTraumaTherapistRoute: typeof AustinTraumaTherapistRoute
  ChristianCounselingRoute: typeof ChristianCounselingRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/christian-counseling': {
      id: '/christian-counseling'
      path: '/christian-counseling'
      fullPath: '/christian-counseling'
      preLoaderRoute: typeof ChristianCounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-trauma-therapist': {
      id: '/austin-trauma-therapist'
      path: '/austin-trauma-therapist'
      fullPath: '/austin-trauma-therapist'
      preLoaderRoute: typeof AustinTraumaTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-therapy': {
      id: '/austin-therapy'
      path: '/austin-therapy'
      fullPath: '/austin-therapy'
      preLoaderRoute: typeof AustinTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-therapist': {
      id: '/austin-therapist'
      path: '/austin-therapist'
      fullPath: '/austin-therapist'
      preLoaderRoute: typeof AustinTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-christian-therapist': {
      id: '/austin-christian-therapist'
      path: '/austin-christian-therapist'
      fullPath: '/austin-christian-therapist'
      preLoaderRoute: typeof AustinChristianTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  AustinChristianTherapistRoute: AustinChristianTherapistRoute,
  AustinTherapistRoute: AustinTherapistRoute,
  AustinTherapyRoute: AustinTherapyRoute,
  AustinTraumaTherapistRoute: AustinTraumaTherapistRoute,
  ChristianCounselingRoute: ChristianCounselingRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
