/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsIfsTherapyRouteImport } from './routes/what-is-ifs-therapy'
import { Route as WhatIsEmdrRouteImport } from './routes/what-is-emdr'
import { Route as TraumaTherapyAustinGuideRouteImport } from './routes/trauma-therapy-austin-guide'
import { Route as TraumaTherapyAustinRouteImport } from './routes/trauma-therapy-austin'
import { Route as TraumaCounselingAustinRouteImport } from './routes/trauma-counseling-austin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as FirstTherapySessionRouteImport } from './routes/first-therapy-session'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CostOfTherapyAustinRouteImport } from './routes/cost-of-therapy-austin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChristianCounselingAustinRouteImport } from './routes/christian-counseling-austin'
import { Route as ChristianCounselingRouteImport } from './routes/christian-counseling'
import { Route as AustinTraumaTherapyRouteImport } from './routes/austin-trauma-therapy'
import { Route as AustinTraumaTherapistRouteImport } from './routes/austin-trauma-therapist'
import { Route as AustinTherapyRouteImport } from './routes/austin-therapy'
import { Route as AustinTherapistRouteImport } from './routes/austin-therapist'
import { Route as AustinCounselingRouteImport } from './routes/austin-counseling'
import { Route as AustinChristianTherapistRouteImport } from './routes/austin-christian-therapist'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AnxietyTherapyAustinRouteImport } from './routes/anxiety-therapy-austin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ResourcesMediaRouteImport } from './routes/resources.media'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WhatIsIfsTherapyRoute = WhatIsIfsTherapyRouteImport.update({
  id: '/what-is-ifs-therapy',
  path: '/what-is-ifs-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsEmdrRoute = WhatIsEmdrRouteImport.update({
  id: '/what-is-emdr',
  path: '/what-is-emdr',
  getParentRoute: () => rootRouteImport,
} as any)
const TraumaTherapyAustinGuideRoute =
  TraumaTherapyAustinGuideRouteImport.update({
    id: '/trauma-therapy-austin-guide',
    path: '/trauma-therapy-austin-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const TraumaTherapyAustinRoute = TraumaTherapyAustinRouteImport.update({
  id: '/trauma-therapy-austin',
  path: '/trauma-therapy-austin',
  getParentRoute: () => rootRouteImport,
} as any)
const TraumaCounselingAustinRoute = TraumaCounselingAustinRouteImport.update({
  id: '/trauma-counseling-austin',
  path: '/trauma-counseling-austin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstTherapySessionRoute = FirstTherapySessionRouteImport.update({
  id: '/first-therapy-session',
  path: '/first-therapy-session',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CostOfTherapyAustinRoute = CostOfTherapyAustinRouteImport.update({
  id: '/cost-of-therapy-austin',
  path: '/cost-of-therapy-austin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChristianCounselingAustinRoute =
  ChristianCounselingAustinRouteImport.update({
    id: '/christian-counseling-austin',
    path: '/christian-counseling-austin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChristianCounselingRoute = ChristianCounselingRouteImport.update({
  id: '/christian-counseling',
  path: '/christian-counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinTraumaTherapyRoute = AustinTraumaTherapyRouteImport.update({
  id: '/austin-trauma-therapy',
  path: '/austin-trauma-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinTraumaTherapistRoute = AustinTraumaTherapistRouteImport.update({
  id: '/austin-trauma-therapist',
  path: '/austin-trauma-therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinTherapyRoute = AustinTherapyRouteImport.update({
  id: '/austin-therapy',
  path: '/austin-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinTherapistRoute = AustinTherapistRouteImport.update({
  id: '/austin-therapist',
  path: '/austin-therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinCounselingRoute = AustinCounselingRouteImport.update({
  id: '/austin-counseling',
  path: '/austin-counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinChristianTherapistRoute =
  AustinChristianTherapistRouteImport.update({
    id: '/austin-christian-therapist',
    path: '/austin-christian-therapist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AnxietyTherapyAustinRoute = AnxietyTherapyAustinRouteImport.update({
  id: '/anxiety-therapy-austin',
  path: '/anxiety-therapy-austin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesMediaRoute = ResourcesMediaRouteImport.update({
  id: '/resources/media',
  path: '/resources/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anxiety-therapy-austin': typeof AnxietyTherapyAustinRoute
  '/approach': typeof ApproachRoute
  '/austin-christian-therapist': typeof AustinChristianTherapistRoute
  '/austin-counseling': typeof AustinCounselingRoute
  '/austin-therapist': typeof AustinTherapistRoute
  '/austin-therapy': typeof AustinTherapyRoute
  '/austin-trauma-therapist': typeof AustinTraumaTherapistRoute
  '/austin-trauma-therapy': typeof AustinTraumaTherapyRoute
  '/christian-counseling': typeof ChristianCounselingRoute
  '/christian-counseling-austin': typeof ChristianCounselingAustinRoute
  '/contact': typeof ContactRoute
  '/cost-of-therapy-austin': typeof CostOfTherapyAustinRoute
  '/faq': typeof FaqRoute
  '/first-therapy-session': typeof FirstTherapySessionRoute
  '/schedule': typeof ScheduleRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trauma-counseling-austin': typeof TraumaCounselingAustinRoute
  '/trauma-therapy-austin': typeof TraumaTherapyAustinRoute
  '/trauma-therapy-austin-guide': typeof TraumaTherapyAustinGuideRoute
  '/what-is-emdr': typeof WhatIsEmdrRoute
  '/what-is-ifs-therapy': typeof WhatIsIfsTherapyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/media': typeof ResourcesMediaRoute
  '/blog/': typeof BlogIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anxiety-therapy-austin': typeof AnxietyTherapyAustinRoute
  '/approach': typeof ApproachRoute
  '/austin-christian-therapist': typeof AustinChristianTherapistRoute
  '/austin-counseling': typeof AustinCounselingRoute
  '/austin-therapist': typeof AustinTherapistRoute
  '/austin-therapy': typeof AustinTherapyRoute
  '/austin-trauma-therapist': typeof AustinTraumaTherapistRoute
  '/austin-trauma-therapy': typeof AustinTraumaTherapyRoute
  '/christian-counseling': typeof ChristianCounselingRoute
  '/christian-counseling-austin': typeof ChristianCounselingAustinRoute
  '/contact': typeof ContactRoute
  '/cost-of-therapy-austin': typeof CostOfTherapyAustinRoute
  '/faq': typeof FaqRoute
  '/first-therapy-session': typeof FirstTherapySessionRoute
  '/schedule': typeof ScheduleRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trauma-counseling-austin': typeof TraumaCounselingAustinRoute
  '/trauma-therapy-austin': typeof TraumaTherapyAustinRoute
  '/trauma-therapy-austin-guide': typeof TraumaTherapyAustinGuideRoute
  '/what-is-emdr': typeof WhatIsEmdrRoute
  '/what-is-ifs-therapy': typeof WhatIsIfsTherapyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/media': typeof ResourcesMediaRoute
  '/blog': typeof BlogIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anxiety-therapy-austin': typeof AnxietyTherapyAustinRoute
  '/approach': typeof ApproachRoute
  '/austin-christian-therapist': typeof AustinChristianTherapistRoute
  '/austin-counseling': typeof AustinCounselingRoute
  '/austin-therapist': typeof AustinTherapistRoute
  '/austin-therapy': typeof AustinTherapyRoute
  '/austin-trauma-therapist': typeof AustinTraumaTherapistRoute
  '/austin-trauma-therapy': typeof AustinTraumaTherapyRoute
  '/christian-counseling': typeof ChristianCounselingRoute
  '/christian-counseling-austin': typeof ChristianCounselingAustinRoute
  '/contact': typeof ContactRoute
  '/cost-of-therapy-austin': typeof CostOfTherapyAustinRoute
  '/faq': typeof FaqRoute
  '/first-therapy-session': typeof FirstTherapySessionRoute
  '/schedule': typeof ScheduleRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trauma-counseling-austin': typeof TraumaCounselingAustinRoute
  '/trauma-therapy-austin': typeof TraumaTherapyAustinRoute
  '/trauma-therapy-austin-guide': typeof TraumaTherapyAustinGuideRoute
  '/what-is-emdr': typeof WhatIsEmdrRoute
  '/what-is-ifs-therapy': typeof WhatIsIfsTherapyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/media': typeof ResourcesMediaRoute
  '/blog/': typeof BlogIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anxiety-therapy-austin'
    | '/approach'
    | '/austin-christian-therapist'
    | '/austin-counseling'
    | '/austin-therapist'
    | '/austin-therapy'
    | '/austin-trauma-therapist'
    | '/austin-trauma-therapy'
    | '/christian-counseling'
    | '/christian-counseling-austin'
    | '/contact'
    | '/cost-of-therapy-austin'
    | '/faq'
    | '/first-therapy-session'
    | '/schedule'
    | '/services'
    | '/sitemap.xml'
    | '/trauma-counseling-austin'
    | '/trauma-therapy-austin'
    | '/trauma-therapy-austin-guide'
    | '/what-is-emdr'
    | '/what-is-ifs-therapy'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/resources/media'
    | '/blog/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/anxiety-therapy-austin'
    | '/approach'
    | '/austin-christian-therapist'
    | '/austin-counseling'
    | '/austin-therapist'
    | '/austin-therapy'
    | '/austin-trauma-therapist'
    | '/austin-trauma-therapy'
    | '/christian-counseling'
    | '/christian-counseling-austin'
    | '/contact'
    | '/cost-of-therapy-austin'
    | '/faq'
    | '/first-therapy-session'
    | '/schedule'
    | '/services'
    | '/sitemap.xml'
    | '/trauma-counseling-austin'
    | '/trauma-therapy-austin'
    | '/trauma-therapy-austin-guide'
    | '/what-is-emdr'
    | '/what-is-ifs-therapy'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/resources/media'
    | '/blog'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anxiety-therapy-austin'
    | '/approach'
    | '/austin-christian-therapist'
    | '/austin-counseling'
    | '/austin-therapist'
    | '/austin-therapy'
    | '/austin-trauma-therapist'
    | '/austin-trauma-therapy'
    | '/christian-counseling'
    | '/christian-counseling-austin'
    | '/contact'
    | '/cost-of-therapy-austin'
    | '/faq'
    | '/first-therapy-session'
    | '/schedule'
    | '/services'
    | '/sitemap.xml'
    | '/trauma-counseling-austin'
    | '/trauma-therapy-austin'
    | '/trauma-therapy-austin-guide'
    | '/what-is-emdr'
    | '/what-is-ifs-therapy'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/resources/media'
    | '/blog/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnxietyTherapyAustinRoute: typeof AnxietyTherapyAustinRoute
  ApproachRoute: typeof ApproachRoute
  AustinChristianTherapistRoute: typeof AustinChristianTherapistRoute
  AustinCounselingRoute: typeof AustinCounselingRoute
  AustinTherapistRoute: typeof AustinTherapistRoute
  AustinTherapyRoute: typeof AustinTherapyRoute
  AustinTraumaTherapistRoute: typeof AustinTraumaTherapistRoute
  AustinTraumaTherapyRoute: typeof AustinTraumaTherapyRoute
  ChristianCounselingRoute: typeof ChristianCounselingRoute
  ChristianCounselingAustinRoute: typeof ChristianCounselingAustinRoute
  ContactRoute: typeof ContactRoute
  CostOfTherapyAustinRoute: typeof CostOfTherapyAustinRoute
  FaqRoute: typeof FaqRoute
  FirstTherapySessionRoute: typeof FirstTherapySessionRoute
  ScheduleRoute: typeof ScheduleRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TraumaCounselingAustinRoute: typeof TraumaCounselingAustinRoute
  TraumaTherapyAustinRoute: typeof TraumaTherapyAustinRoute
  TraumaTherapyAustinGuideRoute: typeof TraumaTherapyAustinGuideRoute
  WhatIsEmdrRoute: typeof WhatIsEmdrRoute
  WhatIsIfsTherapyRoute: typeof WhatIsIfsTherapyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesMediaRoute: typeof ResourcesMediaRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-ifs-therapy': {
      id: '/what-is-ifs-therapy'
      path: '/what-is-ifs-therapy'
      fullPath: '/what-is-ifs-therapy'
      preLoaderRoute: typeof WhatIsIfsTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-emdr': {
      id: '/what-is-emdr'
      path: '/what-is-emdr'
      fullPath: '/what-is-emdr'
      preLoaderRoute: typeof WhatIsEmdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trauma-therapy-austin-guide': {
      id: '/trauma-therapy-austin-guide'
      path: '/trauma-therapy-austin-guide'
      fullPath: '/trauma-therapy-austin-guide'
      preLoaderRoute: typeof TraumaTherapyAustinGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trauma-therapy-austin': {
      id: '/trauma-therapy-austin'
      path: '/trauma-therapy-austin'
      fullPath: '/trauma-therapy-austin'
      preLoaderRoute: typeof TraumaTherapyAustinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trauma-counseling-austin': {
      id: '/trauma-counseling-austin'
      path: '/trauma-counseling-austin'
      fullPath: '/trauma-counseling-austin'
      preLoaderRoute: typeof TraumaCounselingAustinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-therapy-session': {
      id: '/first-therapy-session'
      path: '/first-therapy-session'
      fullPath: '/first-therapy-session'
      preLoaderRoute: typeof FirstTherapySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-of-therapy-austin': {
      id: '/cost-of-therapy-austin'
      path: '/cost-of-therapy-austin'
      fullPath: '/cost-of-therapy-austin'
      preLoaderRoute: typeof CostOfTherapyAustinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/christian-counseling-austin': {
      id: '/christian-counseling-austin'
      path: '/christian-counseling-austin'
      fullPath: '/christian-counseling-austin'
      preLoaderRoute: typeof ChristianCounselingAustinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/christian-counseling': {
      id: '/christian-counseling'
      path: '/christian-counseling'
      fullPath: '/christian-counseling'
      preLoaderRoute: typeof ChristianCounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-trauma-therapy': {
      id: '/austin-trauma-therapy'
      path: '/austin-trauma-therapy'
      fullPath: '/austin-trauma-therapy'
      preLoaderRoute: typeof AustinTraumaTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-trauma-therapist': {
      id: '/austin-trauma-therapist'
      path: '/austin-trauma-therapist'
      fullPath: '/austin-trauma-therapist'
      preLoaderRoute: typeof AustinTraumaTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-therapy': {
      id: '/austin-therapy'
      path: '/austin-therapy'
      fullPath: '/austin-therapy'
      preLoaderRoute: typeof AustinTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-therapist': {
      id: '/austin-therapist'
      path: '/austin-therapist'
      fullPath: '/austin-therapist'
      preLoaderRoute: typeof AustinTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-counseling': {
      id: '/austin-counseling'
      path: '/austin-counseling'
      fullPath: '/austin-counseling'
      preLoaderRoute: typeof AustinCounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin-christian-therapist': {
      id: '/austin-christian-therapist'
      path: '/austin-christian-therapist'
      fullPath: '/austin-christian-therapist'
      preLoaderRoute: typeof AustinChristianTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anxiety-therapy-austin': {
      id: '/anxiety-therapy-austin'
      path: '/anxiety-therapy-austin'
      fullPath: '/anxiety-therapy-austin'
      preLoaderRoute: typeof AnxietyTherapyAustinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/media': {
      id: '/resources/media'
      path: '/resources/media'
      fullPath: '/resources/media'
      preLoaderRoute: typeof ResourcesMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnxietyTherapyAustinRoute: AnxietyTherapyAustinRoute,
  ApproachRoute: ApproachRoute,
  AustinChristianTherapistRoute: AustinChristianTherapistRoute,
  AustinCounselingRoute: AustinCounselingRoute,
  AustinTherapistRoute: AustinTherapistRoute,
  AustinTherapyRoute: AustinTherapyRoute,
  AustinTraumaTherapistRoute: AustinTraumaTherapistRoute,
  AustinTraumaTherapyRoute: AustinTraumaTherapyRoute,
  ChristianCounselingRoute: ChristianCounselingRoute,
  ChristianCounselingAustinRoute: ChristianCounselingAustinRoute,
  ContactRoute: ContactRoute,
  CostOfTherapyAustinRoute: CostOfTherapyAustinRoute,
  FaqRoute: FaqRoute,
  FirstTherapySessionRoute: FirstTherapySessionRoute,
  ScheduleRoute: ScheduleRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TraumaCounselingAustinRoute: TraumaCounselingAustinRoute,
  TraumaTherapyAustinRoute: TraumaTherapyAustinRoute,
  TraumaTherapyAustinGuideRoute: TraumaTherapyAustinGuideRoute,
  WhatIsEmdrRoute: WhatIsEmdrRoute,
  WhatIsIfsTherapyRoute: WhatIsIfsTherapyRoute,
  BlogSlugRoute: BlogSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesMediaRoute: ResourcesMediaRoute,
  BlogIndexRoute: BlogIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
